### ISSUE TITLE
🐞 [2023.03.16] storybook에서 withRouter 관련 오류 발생 #22

### ISSUE THREAD

**Issue by kimzeze** [Lab20-Mosobamboo/Monstera#22]
## 문제 상황
1. develop 브랜치를 pull 하였을 때 기존에 세팅되어있던 preview.js 파일의 import {withRouter} 가 제거되어있었습니다. 
2. merge하는 과정에서 기존의 preview.js에서의 충돌이 있어 제거된 것 같습니다.
3. 따라서 Link 컴포넌트가 Storybook에서 정상 동작하지 않는 것을 확인하였습니다.

## 코드

<img width="1379" alt="스크린샷 2023-03-16 17 12 42" src="https://user-images.githubusercontent.com/96248861/225554881-3b5cd02b-4c2f-4a7b-9b43-d5623664a0fa.png">
<img width="1125" alt="스크린샷 2023-03-16 17 13 31" src="https://user-images.githubusercontent.com/96248861/225555067-9405a25b-56b9-4fb2-9f50-0280eee7da7c.png">

``` import { withRouter } from 'storybook-addon-react-router-v6'; ``` 가 제거되어 있습니다.

**Comment by kimzeze** [comment]
1번라인에 withRouter를 다시 선언해주고 스토리북에서 테스트시 정상 동작하는 것을 확인했습니다.

<img width="878" alt="image" src="https://user-images.githubusercontent.com/96248861/225556137-e5aec1b1-8fcb-4652-bdb7-cb04853f0aa6.png">
<img width="2104" alt="image" src="https://user-images.githubusercontent.com/96248861/225556333-c1105204-96ae-41cf-a86a-78724e6f08ff.png">


정상 동작하는 preview.js 코드도 함께 첨부합니다.

```
import { withRouter } from 'storybook-addon-react-router-v6';

/** @type { import('@storybook/react').Preview } */
const preview = {
  parameters: {
    backgrounds: {
      default: 'light',
    },
    actions: { argTypesRegex: '^on[A-Z].*' },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/,
      },
    },
  },
};

export default preview;

export const decorators = [withRouter];

export const parameters = {
  reactRouter: {
    routePath: '/',
  },
};

```

**Comment by codewarf** [comment]
고생하셨습니다 ㅎㅎ
