### ISSUE TITLE
🐞 [2023.03.21] App.jsx에서 export default 가 중복으로 선언되었습니다. #37

### ISSUE THREAD

**Issue by kimzeze** [Lab20-Mosobamboo/Monstera#37]
## 문제 상황

1. GlobalStyles가 App.jsx에 import도 되어있고 동시에 내용에 GlobalStyles로 export하는 코드가 포함되어있습니다.
`src/App.jsx:10:6: ERROR: The symbol "GlobalStyles" has already been declared`

3. export default를 통하여 GlobalStyles를 내보내주고 있어서 아래와 같은 오류가 나는 것 같습니다.
`src/App.jsx:51:7: ERROR: Multiple exports with the same name "default"`

## 코드
코드를 올릴 때, VS Code 캡쳐본과 함께 해당 코드를 복사해서 올려주세요. 
에러메시지가 있는 경우, 에러메시지 캡쳐본과 함께 에러메시지를 복사해서 올려주세요.

<img width="629" alt="image" src="https://user-images.githubusercontent.com/96248861/226606904-9bb35049-08a3-4bbf-a20d-f873056d1ec9.png">
<img width="636" alt="image" src="https://user-images.githubusercontent.com/96248861/226607035-6c20c2ec-2c48-404e-9bb5-438ae19a2bc0.png">

**Comment by codewarf** [comment]
중복선인 확인했습니다 수정해서 올렸습니다 글로벌스타일 파일을 따로 빼서 만들었는데 app.jsx에서 지우지 않았던 것 같습니다
